# Generated by Django 3.2.7 on 2023-03-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='トーナメント名')),
                ('comment', models.CharField(blank=True, max_length=100, verbose_name='トーナメントに関する補足')),
                ('category', models.CharField(max_length=30, verbose_name='カテゴリー')),
                ('link_list_str', models.TextField(verbose_name='動画リンク')),
                ('thumbnail_list_str', models.TextField(verbose_name='サムネ')),
                ('title_list_str', models.TextField(verbose_name='タイトル')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
